landing                 : false
title                   : Notes on Cloud Computing
author                  : Carles Loriente
url                     : "https://www.notesoncloudcomputing.com"
baseurl                 : "/" 
timezone                : "Europe/Madrid"
description             : A collection of curated opinions and code snippets on cloud tech <br>Bridging knowledge and implementation for enthusiasts and professionals alike
full_description        : >
 A collection of curated opinions and code snippets on cloud tech. <br>Bridging knowledge and implementation for enthusiasts and professionals alike.
gh_repository           : https://github.com/carlesloriente/carlesloriente.github.io/
encoding                : "utf-8"
locale                  : "en-US"
lang                    : "en"
formemail               : xwkglaqr
permalink               : pretty

# Manifest
name                    : "Notes on Cloud Computing"
short_name              : "NOCC"
language                : "en"
lang_direction          : "ltr"
color                   : "#FFFFFF"

# Features
critical_css            : false

#SideProjects
tjt_version             : v2.4.0
tjt_name                : Top Jekyll Themes
tjt_url                 : https://www.topjekyllthemes.com

# Theme Notice (please don't remove it ;))
theme_name              : Nocc Bootstrap Theme
theme_url               : https://bootstrap-theme.notesoncloudcomputing.com/
theme_logo              : "/assets/vendor/nocc-bootstrap-theme/images/nocc/nocc_logo.webp"
theme_author            : Carles Loriente
theme_author_url        : https://www.notesoncloudcomputing.com/about/
theme_npm_version       : v2.0.2
theme_npm_package       : https://www.npmjs.com/package/nocc-bootstrap-theme
theme_gem_version       : v2.0.2
theme gem_package       : https://rubygems.org/gems/jekyll-theme-nocc/
theme_bundle_version    : v1.3.9
theme_bundle_name       : Site Bundle for Jekyll
theme_bundle_repo       : https://github.com/carlesloriente/bootstrap-theme-jekyll/
theme_bundle_download   : https://github.com/carlesloriente/bootstrap-theme-jekyll/archive/refs/heads/main.zip

# Social Profiles
email                   : "fi1nziulf@mozmail.com"
twitter_username        : godarthvader
github_username         : carlesloriente
linkedin_username       : carles-loriente
kofi                    : S6S1O2GTU

# Add your google-analytics ID here to activate google analytics
google_site_verification: FOgdVCuoL8lBB0LjlVT7D-R-vavtFjwbRGc85DbJLfE
google_analytics        : G-YZN6D91Z4N
google_adsense_account  : ca-pub-4415526626304056
google_tag_id           : GTM-NGMCZ93D

# Disqus Comments
# Leave shortname blank to disable comments site-wide.
# Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
disqus_shortname        : notes-on-cloud-infrastructure

data_dir                : _data
includes_dir            : _includes
layouts_dir             : _layouts
plugins_dir             : _plugins
tags_dir                : tags

collections:
  posts:
    permalink           : /posts/:name/
    output              : true
  tags:
    permalink           : /tags/:name/
    output              : true

defaults:
  - scope:
      path              : "posts"
      type              : posts
    values:
      layout            : post
  - scope:
      path              : 'assets/**'
    values:
      sitemap           : false

# Markdown Processors
kramdown:
  auto_ids              : true
  entity_output         : as_char
  toc_levels            : [1, 2, 3, 4, 5, 6]
  smart_quotes          : lsquo,rsquo,ldquo,rdquo
  input                 : GFM
  hard_wrap             : false
  footnote_nr           : 1
  show_warnings         : false

# Build settings
paginate                : 20
paginate_path           : "/notes/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-toc

sass:
  load_paths:
    - ./_sass
  style                 : compressed

exclude: ["bd27dc68a01f40a4826fed8a45e2316e.txt", "AUTHORS.md", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "CODEOWNERS", "LICENSE", "package.json", "package-lock.json", "README.md", "resume.html", "SECURITY.md", "techstack.md", "techstack.yml", "WORKFLOW.md", "bin", "gists", "node_modules", "ahrefs_6f259190b96e078821b745c49ce5f85e18b0d0addfd0ea6778eeafc411f82bee", "BingSiteAuth.xml", "CNAME", "yandex_f833f55647ca1132.html", "Gemfile", "Gemfile.lock", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
