title:              Notes on cloud infrastructure
description:        
author:             Carles Loriente
baseurl:            ""
#url:                "http://localhost:4000"
url:                "https://carlesloriente.github.io"

# Social Profiles
twitter_username:   godarthvader
github_username:    carlesloriente
facebook_username:  
linkedin_username:  carles-loriente

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-147965228-1 # out your google-analytics code

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: 4421358

    # Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Build settings
theme:              jekyll-theme-clean-blog
