name: "IndexNow"
on:
  schedule: # Run workflow automatically
  - cron: '0 0 * * *' # Runs every day at 0, on the hour. Scheduled in UTC.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://www.notesoncloudcomputing.com/sitemap.xml"
          since: 1
          since-unit: "week"
          key: ${{ secrets.INDEXNOW_KEY }}
